apiVersion: v1
kind: Secret
metadata:
  name: {{ include "archer-database.fullname" . }}
  labels:
    {{- include "archer-database.labels" . | nindent 4 }}
type: Opaque
stringData:
  mysql-root-password: {{ .Values.auth.rootPassword | quote }}
  mysql-password: {{ .Values.auth.password | quote }}
